name: ManualWorkflow
on: [workflow_dispatch]
jobs:
  # Build and test the code
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      # Compile the code
      - name: Compile code
        run: mvn install -DskipTests

      # Gradle check
      - name: Check
        run: mvn test
